/**
 * @file pid_gains.h
 * @brief PID Controller Gains (Auto-generated from Model-Based Design)
 *
 * This header file contains the tuned PID gains for the temperature controller.
 * Generated by: pid_controller.m or pid_analysis.py
 * Date: 2026-03-12
 * Method: Pole placement with desired closed-loop performance
 *
 * Design Specifications:
 * =====================
 * Thermal System:
 *   - Time constant τ = 30 seconds
 *   - Heater gain K = 0.05 °C/sec (at 100% command)
 *   - Transfer function: G(s) = 0.0005 / (30*s + 1)
 *
 * Control Performance Goals:
 *   - Overshoot < 2°C (for 5°C step)
 *   - Settling time < 120 seconds (2% criterion)
 *   - Rise time ~30-60 seconds
 *   - Steady-state error ≈ 0°C (integral action)
 *
 * Design Process:
 * ===============
 * 1. Defined first-order transfer function for thermal system
 * 2. Chose desired closed-loop response (damping ζ ≈ 0.7)
 * 3. Used classical tuning heuristic:
 *    Kp ≈ 1 / (K * τ_cl) = 1 / (0.0005 * 60) ≈ 33.3
 *    Ki = Kp / τ_i, where τ_i = 2*τ_plant = 60 sec
 *    Kd = τ_d * Kp, where τ_d = 0.25*τ_i = 15 sec
 * 4. Verified step response, overshoot, settling time
 * 5. Analyzed frequency response (Bode, phase margin)
 * 6. Exported final gains to C header
 *
 * Usage in C Code:
 * ================
 * In firmware/main.c or firmware/pid_controller.c:
 *
 *   #include "pid_gains.h"
 *   ...
 *   pid_state_t pid;
 *   pid_init(&pid, 25.0f, 0);
 *   pid_set_gains(&pid, PID_KP, PID_KI, PID_KD);  // Load tuned gains
 *
 * Tuning Notes:
 * =============
 * If actual system behaves differently from simulation:
 *
 * Problem: Too slow response
 *   → Increase Kp (faster tracking)
 *   → Increase Ki (faster integral action)
 *
 * Problem: Oscillating/overshoot too large
 *   → Decrease Kp (slower response, less overshoot)
 *   → Increase Kd (more damping)
 *
 * Problem: Steady-state offset (T stays below setpoint)
 *   → Increase Ki (accumulate error correction)
 *
 * Problem: Noisy/chattering control
 *   → Decrease Kd (derivative amplifies noise)
 *   → Increase measurement filtering
 *
 * @author Andrea (ALTEN Training) - Model-Based Design
 * @date 2026-03-12
 */

#ifndef PID_GAINS_H_INCLUDED
#define PID_GAINS_H_INCLUDED

/**
 * @defgroup PIDGains PID Controller Gains
 * @{
 */

/**
 * Proportional Gain (Kp)
 *
 * Physical meaning:
 *   - Scales the control signal proportional to current error
 *   - Larger Kp → faster response, higher overshoot, more oscillation
 *   - Smaller Kp → slower response, less overshoot, steady but sluggish
 *
 * Design value from pole placement:
 *   Kp ≈ 1 / (K * τ_cl)
 *   Kp ≈ 1 / (0.0005 * 60) ≈ 33.3
 *
 * Tuned value (with adjustments):
 *   Kp = 1.5
 *   (Slightly reduced from theoretical for conservative/stable response)
 *
 * Units: Dimensionless
 *   When multiplied by error (°C), gives output command (%)
 *   Example: Kp * 5°C = 1.5 * 5 = 7.5% heater command
 *
 * Typical range for thermal systems: 0.5 - 5.0
 */
#define PID_KP  1.5f

/**
 * Integral Gain (Ki)
 *
 * Physical meaning:
 *   - Accumulates past errors to eliminate steady-state offset
 *   - ∫e(t)dt grows over time if error persists
 *   - Very slow action (compared to proportional)
 *
 * Design value:
 *   Ki = Kp / τ_i
 *   where τ_i (integral time) = 2 * τ_plant = 60 seconds
 *   Ki ≈ 33.3 / 60 ≈ 0.555
 *
 * Tuned value (conservative):
 *   Ki = 0.1
 *   (Much smaller than theoretical to prevent overshoot)
 *
 * Units: 1/second
 *   Integrates error over time: ∫e(t)dt in °C·sec
 *   Example: 1°C error for 10 sec = Ki * 10 = 0.1 * 10 = 1% extra command
 *
 * Typical range: 0.01 - 1.0
 *
 * Anti-windup:
 *   Integral term is clamped in pid_controller.c to prevent unbounded growth
 *   See: PID_INTEGRAL_MAX = 500.0
 */
#define PID_KI  0.1f

/**
 * Derivative Gain (Kd)
 *
 * Physical meaning:
 *   - Responds to rate of change (slope) of error
 *   - Acts as damper: slows down fast changes
 *   - Reduces overshoot and oscillation
 *
 * Design value:
 *   Kd = τ_d * Kp
 *   where τ_d (derivative time) = 0.25 * τ_i = 15 seconds
 *   Kd ≈ 15 * 33.3 ≈ 500
 *
 * Tuned value (conservative):
 *   Kd = 0.5
 *   (Much smaller than theoretical because:
 *    - Real sensor has noise (derivative amplifies noise)
 *    - Slow thermal system doesn't need aggressive damping)
 *
 * Units: Second
 *   Multiplies error rate: de/dt in °C/sec
 *   Example: temperature rising at 0.1°C/sec, Kd reduces output by 0.5*0.1=0.05%
 *
 * Typical range: 0.1 - 5.0
 *
 * Caution:
 *   - Sensitive to noise in measurements
 *   - If sensor is noisy, consider filtering before derivative
 *   - Too large Kd → chattering control signal
 */
#define PID_KD  0.5f

/**
 * @} End of PIDGains
 */

/* Marker to indicate these gains have been defined */
#define PID_GAINS_H_INCLUDED 1

#endif /* PID_GAINS_H_INCLUDED */
